# Generated by Django 4.2.19 on 2026-07-30 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0002_sessionreconnectlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('video_url', models.URLField(help_text='Video File URL or Storage Path', max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('Pending Upload', 'Pending Upload'), ('Processing', 'Processing'), ('Encoding Completed', 'Encoding Completed'), ('Ready', 'Ready for Playback'), ('Failed', 'Failed Processing')], default='Pending Upload', max_length=30)),
                ('recording_start_time', models.DateTimeField(blank=True, null=True)),
                ('recording_end_time', models.DateTimeField(blank=True, null=True)),
                ('recording_date', models.DateField(auto_now_add=True)),
                ('playback_count', models.PositiveIntegerField(default=0)),
                ('download_enabled', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('Public Batch', 'Public Batch'), ('Private Trainer', 'Private Trainer')], default='Public Batch', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='classroom.classroomsession')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_duration', models.PositiveIntegerField(default=0, help_text='Watch duration in seconds')),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='recordings.recording')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recording', 'user')},
            },
        ),
    ]
