# Generated by Django 4.2.19 on 2026-07-22 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSession',
            fields=[
                ('id', models.CharField(default='session_101', max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Live Interactive Class', max_length=255)),
                ('is_live', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('allow_unmute', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingRoomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_users', to='classroom.classroomsession')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='classroom.classroomsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Trainer', 'Trainer'), ('Student', 'Student')], default='Student', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disconnected', 'Disconnected'), ('Removed', 'Removed')], default='Active', max_length=20)),
                ('is_muted', models.BooleanField(default=True)),
                ('is_camera_on', models.BooleanField(default=False)),
                ('has_raised_hand', models.BooleanField(default=False)),
                ('can_speak', models.BooleanField(default=True)),
                ('can_chat', models.BooleanField(default=True)),
                ('can_screen_share', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='classroom.classroomsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'email')},
            },
        ),
    ]
