# Generated by Django 4.2.19 on 2026-07-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReconnectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_role', models.CharField(default='Trainer', max_length=20)),
                ('disconnected_at', models.DateTimeField(auto_now_add=True)),
                ('reconnected_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Reconnecting', 'Reconnecting'), ('Restored', 'Restored'), ('TimedOut', 'TimedOut')], default='Reconnecting', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconnect_logs', to='classroom.classroomsession')),
            ],
            options={
                'ordering': ['-disconnected_at'],
            },
        ),
    ]
